# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ASResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ASResponse.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x41SResponse.proto\"1\n\nASResponse\x12\x13\n\x0buser_header\x18\x01 \x02(\x0c\x12\x0e\n\x06ticket\x18\x02 \x02(\x0c')
)




_ASRESPONSE = _descriptor.Descriptor(
  name='ASResponse',
  full_name='ASResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_header', full_name='ASResponse.user_header', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='ASResponse.ticket', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['ASResponse'] = _ASRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ASResponse = _reflection.GeneratedProtocolMessageType('ASResponse', (_message.Message,), dict(
  DESCRIPTOR = _ASRESPONSE,
  __module__ = 'ASResponse_pb2'
  # @@protoc_insertion_point(class_scope:ASResponse)
  ))
_sym_db.RegisterMessage(ASResponse)


# @@protoc_insertion_point(module_scope)
