# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Kerberos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Kerberos.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0eKerberos.proto\".\n\rUserASRequest\x12\x0c\n\x04id_c\x18\x01 \x02(\t\x12\x0f\n\x07request\x18\x02 \x02(\x0c\";\n\x11UserASRequestData\x12\x0c\n\x04id_s\x18\x01 \x02(\t\x12\x0b\n\x03t_r\x18\x02 \x02(\x01\x12\x0b\n\x03n_1\x18\x03 \x02(\x0c\"2\n\nASResponse\x12\x13\n\x0buser_header\x18\x01 \x02(\x0c\x12\x0f\n\x07t_c_tgs\x18\x02 \x02(\x0c\"4\n\x14\x41SResponseUserHeader\x12\x0f\n\x07k_c_tgs\x18\x01 \x02(\x0c\x12\x0b\n\x03n_1\x18\x02 \x02(\x0c\">\n\x10\x41SResponseTicket\x12\x0c\n\x04id_c\x18\x01 \x02(\t\x12\x0b\n\x03t_r\x18\x02 \x02(\x01\x12\x0f\n\x07k_c_tgs\x18\x03 \x02(\x0c\"2\n\x0eUserTGSRequest\x12\x0f\n\x07request\x18\x01 \x02(\x0c\x12\x0f\n\x07t_c_tgs\x18\x02 \x02(\x0c\"J\n\x12UserTGSRequestData\x12\x0c\n\x04id_c\x18\x01 \x02(\t\x12\x0c\n\x04id_s\x18\x02 \x02(\t\x12\x0b\n\x03t_r\x18\x03 \x02(\x01\x12\x0b\n\x03n_2\x18\x04 \x02(\x0c\"1\n\x0bTGSResponse\x12\x13\n\x0buser_header\x18\x01 \x02(\x0c\x12\r\n\x05t_c_s\x18\x02 \x02(\x0c\"@\n\x15TGSResponseUserHeader\x12\r\n\x05k_c_s\x18\x01 \x02(\x0c\x12\x0b\n\x03t_a\x18\x02 \x02(\x01\x12\x0b\n\x03n_2\x18\x03 \x02(\x0c\"=\n\x11TGSResponseTicket\x12\x0c\n\x04id_c\x18\x01 \x02(\t\x12\x0b\n\x03t_a\x18\x02 \x02(\x01\x12\r\n\x05k_c_s\x18\x03 \x02(\x0c\"4\n\x12UserServiceRequest\x12\x0f\n\x07request\x18\x01 \x02(\x0c\x12\r\n\x05t_c_s\x18\x02 \x02(\x0c\"M\n\x16UserServiceRequestData\x12\x0c\n\x04id_c\x18\x01 \x02(\t\x12\x0b\n\x03t_r\x18\x02 \x02(\x01\x12\x0b\n\x03s_r\x18\x03 \x02(\t\x12\x0b\n\x03n_3\x18\x04 \x02(\x0c\"#\n\x0fServiceResponse\x12\x10\n\x08response\x18\x01 \x02(\x0c\"8\n\x13ServiceResponseData\x12\x14\n\x0cresponse_str\x18\x01 \x02(\t\x12\x0b\n\x03n_3\x18\x02 \x02(\x0c')
)




_USERASREQUEST = _descriptor.Descriptor(
  name='UserASRequest',
  full_name='UserASRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_c', full_name='UserASRequest.id_c', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='UserASRequest.request', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=64,
)


_USERASREQUESTDATA = _descriptor.Descriptor(
  name='UserASRequestData',
  full_name='UserASRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_s', full_name='UserASRequestData.id_s', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_r', full_name='UserASRequestData.t_r', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_1', full_name='UserASRequestData.n_1', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=125,
)


_ASRESPONSE = _descriptor.Descriptor(
  name='ASResponse',
  full_name='ASResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_header', full_name='ASResponse.user_header', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_c_tgs', full_name='ASResponse.t_c_tgs', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=177,
)


_ASRESPONSEUSERHEADER = _descriptor.Descriptor(
  name='ASResponseUserHeader',
  full_name='ASResponseUserHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k_c_tgs', full_name='ASResponseUserHeader.k_c_tgs', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_1', full_name='ASResponseUserHeader.n_1', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=231,
)


_ASRESPONSETICKET = _descriptor.Descriptor(
  name='ASResponseTicket',
  full_name='ASResponseTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_c', full_name='ASResponseTicket.id_c', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_r', full_name='ASResponseTicket.t_r', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k_c_tgs', full_name='ASResponseTicket.k_c_tgs', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=295,
)


_USERTGSREQUEST = _descriptor.Descriptor(
  name='UserTGSRequest',
  full_name='UserTGSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='UserTGSRequest.request', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_c_tgs', full_name='UserTGSRequest.t_c_tgs', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=347,
)


_USERTGSREQUESTDATA = _descriptor.Descriptor(
  name='UserTGSRequestData',
  full_name='UserTGSRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_c', full_name='UserTGSRequestData.id_c', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_s', full_name='UserTGSRequestData.id_s', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_r', full_name='UserTGSRequestData.t_r', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_2', full_name='UserTGSRequestData.n_2', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=423,
)


_TGSRESPONSE = _descriptor.Descriptor(
  name='TGSResponse',
  full_name='TGSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_header', full_name='TGSResponse.user_header', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_c_s', full_name='TGSResponse.t_c_s', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=474,
)


_TGSRESPONSEUSERHEADER = _descriptor.Descriptor(
  name='TGSResponseUserHeader',
  full_name='TGSResponseUserHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k_c_s', full_name='TGSResponseUserHeader.k_c_s', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_a', full_name='TGSResponseUserHeader.t_a', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_2', full_name='TGSResponseUserHeader.n_2', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=540,
)


_TGSRESPONSETICKET = _descriptor.Descriptor(
  name='TGSResponseTicket',
  full_name='TGSResponseTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_c', full_name='TGSResponseTicket.id_c', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_a', full_name='TGSResponseTicket.t_a', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k_c_s', full_name='TGSResponseTicket.k_c_s', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=603,
)


_USERSERVICEREQUEST = _descriptor.Descriptor(
  name='UserServiceRequest',
  full_name='UserServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='UserServiceRequest.request', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_c_s', full_name='UserServiceRequest.t_c_s', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=657,
)


_USERSERVICEREQUESTDATA = _descriptor.Descriptor(
  name='UserServiceRequestData',
  full_name='UserServiceRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_c', full_name='UserServiceRequestData.id_c', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_r', full_name='UserServiceRequestData.t_r', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='s_r', full_name='UserServiceRequestData.s_r', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_3', full_name='UserServiceRequestData.n_3', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=659,
  serialized_end=736,
)


_SERVICERESPONSE = _descriptor.Descriptor(
  name='ServiceResponse',
  full_name='ServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ServiceResponse.response', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=773,
)


_SERVICERESPONSEDATA = _descriptor.Descriptor(
  name='ServiceResponseData',
  full_name='ServiceResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_str', full_name='ServiceResponseData.response_str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_3', full_name='ServiceResponseData.n_3', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=831,
)

DESCRIPTOR.message_types_by_name['UserASRequest'] = _USERASREQUEST
DESCRIPTOR.message_types_by_name['UserASRequestData'] = _USERASREQUESTDATA
DESCRIPTOR.message_types_by_name['ASResponse'] = _ASRESPONSE
DESCRIPTOR.message_types_by_name['ASResponseUserHeader'] = _ASRESPONSEUSERHEADER
DESCRIPTOR.message_types_by_name['ASResponseTicket'] = _ASRESPONSETICKET
DESCRIPTOR.message_types_by_name['UserTGSRequest'] = _USERTGSREQUEST
DESCRIPTOR.message_types_by_name['UserTGSRequestData'] = _USERTGSREQUESTDATA
DESCRIPTOR.message_types_by_name['TGSResponse'] = _TGSRESPONSE
DESCRIPTOR.message_types_by_name['TGSResponseUserHeader'] = _TGSRESPONSEUSERHEADER
DESCRIPTOR.message_types_by_name['TGSResponseTicket'] = _TGSRESPONSETICKET
DESCRIPTOR.message_types_by_name['UserServiceRequest'] = _USERSERVICEREQUEST
DESCRIPTOR.message_types_by_name['UserServiceRequestData'] = _USERSERVICEREQUESTDATA
DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
DESCRIPTOR.message_types_by_name['ServiceResponseData'] = _SERVICERESPONSEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserASRequest = _reflection.GeneratedProtocolMessageType('UserASRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERASREQUEST,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:UserASRequest)
  ))
_sym_db.RegisterMessage(UserASRequest)

UserASRequestData = _reflection.GeneratedProtocolMessageType('UserASRequestData', (_message.Message,), dict(
  DESCRIPTOR = _USERASREQUESTDATA,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:UserASRequestData)
  ))
_sym_db.RegisterMessage(UserASRequestData)

ASResponse = _reflection.GeneratedProtocolMessageType('ASResponse', (_message.Message,), dict(
  DESCRIPTOR = _ASRESPONSE,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:ASResponse)
  ))
_sym_db.RegisterMessage(ASResponse)

ASResponseUserHeader = _reflection.GeneratedProtocolMessageType('ASResponseUserHeader', (_message.Message,), dict(
  DESCRIPTOR = _ASRESPONSEUSERHEADER,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:ASResponseUserHeader)
  ))
_sym_db.RegisterMessage(ASResponseUserHeader)

ASResponseTicket = _reflection.GeneratedProtocolMessageType('ASResponseTicket', (_message.Message,), dict(
  DESCRIPTOR = _ASRESPONSETICKET,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:ASResponseTicket)
  ))
_sym_db.RegisterMessage(ASResponseTicket)

UserTGSRequest = _reflection.GeneratedProtocolMessageType('UserTGSRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERTGSREQUEST,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:UserTGSRequest)
  ))
_sym_db.RegisterMessage(UserTGSRequest)

UserTGSRequestData = _reflection.GeneratedProtocolMessageType('UserTGSRequestData', (_message.Message,), dict(
  DESCRIPTOR = _USERTGSREQUESTDATA,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:UserTGSRequestData)
  ))
_sym_db.RegisterMessage(UserTGSRequestData)

TGSResponse = _reflection.GeneratedProtocolMessageType('TGSResponse', (_message.Message,), dict(
  DESCRIPTOR = _TGSRESPONSE,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:TGSResponse)
  ))
_sym_db.RegisterMessage(TGSResponse)

TGSResponseUserHeader = _reflection.GeneratedProtocolMessageType('TGSResponseUserHeader', (_message.Message,), dict(
  DESCRIPTOR = _TGSRESPONSEUSERHEADER,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:TGSResponseUserHeader)
  ))
_sym_db.RegisterMessage(TGSResponseUserHeader)

TGSResponseTicket = _reflection.GeneratedProtocolMessageType('TGSResponseTicket', (_message.Message,), dict(
  DESCRIPTOR = _TGSRESPONSETICKET,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:TGSResponseTicket)
  ))
_sym_db.RegisterMessage(TGSResponseTicket)

UserServiceRequest = _reflection.GeneratedProtocolMessageType('UserServiceRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERSERVICEREQUEST,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:UserServiceRequest)
  ))
_sym_db.RegisterMessage(UserServiceRequest)

UserServiceRequestData = _reflection.GeneratedProtocolMessageType('UserServiceRequestData', (_message.Message,), dict(
  DESCRIPTOR = _USERSERVICEREQUESTDATA,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:UserServiceRequestData)
  ))
_sym_db.RegisterMessage(UserServiceRequestData)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVICERESPONSE,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:ServiceResponse)
  ))
_sym_db.RegisterMessage(ServiceResponse)

ServiceResponseData = _reflection.GeneratedProtocolMessageType('ServiceResponseData', (_message.Message,), dict(
  DESCRIPTOR = _SERVICERESPONSEDATA,
  __module__ = 'Kerberos_pb2'
  # @@protoc_insertion_point(class_scope:ServiceResponseData)
  ))
_sym_db.RegisterMessage(ServiceResponseData)


# @@protoc_insertion_point(module_scope)
