# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserServiceRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UserServiceRequest.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18UserServiceRequest.proto\"5\n\x12UserServiceRequest\x12\x0f\n\x07request\x18\x01 \x02(\x0c\x12\x0e\n\x06ticket\x18\x02 \x02(\x0c')
)




_USERSERVICEREQUEST = _descriptor.Descriptor(
  name='UserServiceRequest',
  full_name='UserServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='UserServiceRequest.request', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket', full_name='UserServiceRequest.ticket', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['UserServiceRequest'] = _USERSERVICEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserServiceRequest = _reflection.GeneratedProtocolMessageType('UserServiceRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERSERVICEREQUEST,
  __module__ = 'UserServiceRequest_pb2'
  # @@protoc_insertion_point(class_scope:UserServiceRequest)
  ))
_sym_db.RegisterMessage(UserServiceRequest)


# @@protoc_insertion_point(module_scope)
